import type { PricingTier } from "@/types";

export const PRICING_TIERS: PricingTier[] = [
  {
    id: "gratis",
    name: "Gratis",
    priceMonthly: 0,
    priceYearly: 0,
    description: "Untuk mencoba dan proyek kecil",
    features: [
      "25 sertifikat per bulan",
      "1 desain aktif",
      "QR verifikasi publik",
      "Unduh sebagai PNG",
      "Dukungan komunitas",
    ],
    cta: "Mulai Gratis",
    highlighted: false,
  },
  {
    id: "pro",
    name: "Pro",
    priceMonthly: 149000,
    priceYearly: 119200,
    description: "Untuk tim event dan panitia aktif",
    features: [
      "500 sertifikat per bulan",
      "Semua template siap pakai",
      "QR verifikasi + analitik dasar",
      "Ekspor ZIP batch",
      "Branding khusus (logo & warna)",
      "Dukungan prioritas via email",
    ],
    cta: "Mulai Uji Coba 14 Hari",
    highlighted: true,
  },
  {
    id: "bisnis",
    name: "Bisnis",
    priceMonthly: 379000,
    priceYearly: 303200,
    description: "Untuk HR, divisi pelatihan, dan institusi",
    features: [
      "2.000 sertifikat per bulan",
      "Semua fitur Pro",
      "Kirim ke email peserta (blast)",
      "Analitik lanjutan & ekspor CSV",
      "Akses API & webhook",
      "Onboarding terdampingi",
    ],
    cta: "Hubungi Sales",
    highlighted: false,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    priceMonthly: null,
    priceYearly: null,
    description: "Skala penuh, kontrak kustom",
    features: [
      "Sertifikat tak terbatas",
      "Semua fitur Bisnis",
      "Custom domain verifikasi",
      "SLA 99.9% uptime",
      "Dedicated success manager",
      "Kontrak & faktur kustom",
    ],
    cta: "Jadwalkan Demo",
    highlighted: false,
    dark: true,
  },
];
